/// <reference types="next" />
/// <reference types="next/image-types/global" />

/**
 * Declares plain stylesheet imports.
 *
 * Next's own ambient types declare `*.module.css` (which yields a class-name
 * map) but not a bare `import './globals.css'`, which is a side-effect import
 * with no value. Without this the compiler reports TS2882 on the root layout —
 * the build succeeds either way, since the bundler handles the import, but the
 * editor flags it as an error.
 *
 * The two references above duplicate `next-env.d.ts` on purpose. That file is
 * generated by `next build` and gitignored per Next's convention, so it is
 * absent in a fresh clone until the first build; repeating them here means the
 * editor resolves Next's types immediately after `pnpm install`.
 */
declare module '*.css';
declare module '*.scss';
declare module '*.sass';
